//! Lock file management for reproducible builds
//!
//! The lock file (gotgan.lock) records exact dependency versions
//! to ensure reproducible builds across different machines.

use crate::resolver::ResolvedDep;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;
use thiserror::Error;

/// Lock file name
pub const LOCK_FILE_NAME: &str = "gotgan.lock";

/// Errors during lock file operations
#[derive(Error, Debug)]
pub enum LockError {
    #[error("Failed to read lock file: {0}")]
    ReadError(#[from] std::io::Error),

    #[error("Failed to parse lock file: {0}")]
    ParseError(#[from] toml::de::Error),

    #[error("Failed to serialize lock file: {0}")]
    SerializeError(#[from] toml::ser::Error),

    #[error("Lock file mismatch: {0}")]
    Mismatch(String),
}

/// Lock file structure
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LockFile {
    /// Lock file format version
    pub version: u32,

    /// Locked packages (sorted by name for determinism)
    #[serde(default)]
    pub package: Vec<LockedPackage>,
}

/// A locked package entry
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
pub struct LockedPackage {
    /// Package name
    pub name: String,

    /// Exact version
    pub version: String,

    /// Source path (for path dependencies)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,

    /// Number of source files (for quick validation)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_count: Option<usize>,
}

impl LockFile {
    /// Create a new lock file from resolved dependencies
    pub fn from_resolved(deps: &[ResolvedDep]) -> Self {
        let mut packages: Vec<LockedPackage> = deps
            .iter()
            .map(|dep| LockedPackage {
                name: dep.name.clone(),
                version: dep.version.clone(),
                path: Some(dep.path.to_string_lossy().to_string()),
                source_count: Some(dep.source_files.len()),
            })
            .collect();

        // Sort for deterministic output
        packages.sort();

        Self {
            version: 1,
            package: packages,
        }
    }

    /// Load lock file from path
    pub fn load(path: &Path) -> Result<Self, LockError> {
        let content = fs::read_to_string(path)?;
        let lock: LockFile = toml::from_str(&content)?;
        Ok(lock)
    }

    /// Save lock file to path
    pub fn save(&self, path: &Path) -> Result<(), LockError> {
        let content = toml::to_string_pretty(self)?;
        // Add header comment
        let with_header = format!(
            "# This file is auto-generated by gotgan.\n# Do not edit manually.\n\n{}",
            content
        );
        fs::write(path, with_header)?;
        Ok(())
    }

    /// Check if this lock file matches the resolved dependencies
    pub fn matches(&self, deps: &[ResolvedDep]) -> bool {
        if self.package.len() != deps.len() {
            return false;
        }

        let current = Self::from_resolved(deps);
        self.package == current.package
    }

    /// Get a map of package names to locked versions
    pub fn packages_by_name(&self) -> BTreeMap<String, &LockedPackage> {
        self.package.iter().map(|p| (p.name.clone(), p)).collect()
    }
}

impl Default for LockFile {
    fn default() -> Self {
        Self {
            version: 1,
            package: Vec::new(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn test_lock_file_empty() {
        let lock = LockFile::default();
        assert_eq!(lock.version, 1);
        assert!(lock.package.is_empty());
    }

    #[test]
    fn test_lock_file_from_resolved() {
        let deps = vec![
            ResolvedDep {
                name: "mylib".to_string(),
                version: "0.1.0".to_string(),
                path: PathBuf::from("/path/to/mylib"),
                source_files: vec![PathBuf::from("lib.bmb")],
            },
            ResolvedDep {
                name: "anotherlib".to_string(),
                version: "0.2.0".to_string(),
                path: PathBuf::from("/path/to/another"),
                source_files: vec![],
            },
        ];

        let lock = LockFile::from_resolved(&deps);
        assert_eq!(lock.package.len(), 2);
        // Should be sorted alphabetically
        assert_eq!(lock.package[0].name, "anotherlib");
        assert_eq!(lock.package[1].name, "mylib");
    }

    #[test]
    fn test_lock_file_serialize() {
        let lock = LockFile {
            version: 1,
            package: vec![LockedPackage {
                name: "test".to_string(),
                version: "1.0.0".to_string(),
                path: Some("/test".to_string()),
                source_count: Some(3),
            }],
        };

        let toml = toml::to_string_pretty(&lock).unwrap();
        assert!(toml.contains("name = \"test\""));
        assert!(toml.contains("version = \"1.0.0\""));
    }
}
