//! Project creation and initialization

use crate::config::Manifest;
use std::fs;
use std::path::Path;
use thiserror::Error;

/// Errors that can occur during project operations
#[derive(Error, Debug)]
pub enum ProjectError {
    #[error("Directory already exists: {0}")]
    DirectoryExists(String),

    #[error("Failed to create directory: {0}")]
    CreateDirError(#[from] std::io::Error),

    #[error("Config error: {0}")]
    ConfigError(#[from] crate::config::ConfigError),

    #[error("Project already initialized (gotgan.toml exists)")]
    AlreadyInitialized,

    #[error("Invalid project name: {0}")]
    InvalidName(String),
}

/// Create a new BMB project in the specified directory
pub fn create_project(name: &str, path: &Path, is_lib: bool) -> Result<(), ProjectError> {
    validate_project_name(name)?;

    // Check if directory already exists
    if path.exists() {
        return Err(ProjectError::DirectoryExists(path.display().to_string()));
    }

    // Create project directory structure
    fs::create_dir_all(path)?;
    fs::create_dir_all(path.join("src"))?;

    // Create gotgan.toml
    let manifest = Manifest::new(name);
    manifest.save(&path.join("gotgan.toml"))?;

    // Create source files
    if is_lib {
        create_lib_template(path, name)?;
    } else {
        create_bin_template(path, name)?;
    }

    // Create tests directory
    fs::create_dir_all(path.join("tests"))?;

    println!("Created BMB project `{}` at {}", name, path.display());
    Ok(())
}

/// Initialize a BMB project in an existing directory
pub fn init_project(name: &str, path: &Path, is_lib: bool) -> Result<(), ProjectError> {
    validate_project_name(name)?;

    // Check if already initialized
    let manifest_path = path.join("gotgan.toml");
    if manifest_path.exists() {
        return Err(ProjectError::AlreadyInitialized);
    }

    // Create src directory if it doesn't exist
    let src_path = path.join("src");
    if !src_path.exists() {
        fs::create_dir_all(&src_path)?;
    }

    // Create gotgan.toml
    let manifest = Manifest::new(name);
    manifest.save(&manifest_path)?;

    // Create source files only if they don't exist
    if is_lib {
        let lib_path = src_path.join("lib.bmb");
        if !lib_path.exists() {
            fs::write(&lib_path, generate_lib_content(name))?;
        }
    } else {
        let main_path = src_path.join("main.bmb");
        if !main_path.exists() {
            fs::write(&main_path, generate_main_content(name))?;
        }
    }

    // Create tests directory if it doesn't exist
    let tests_path = path.join("tests");
    if !tests_path.exists() {
        fs::create_dir_all(&tests_path)?;
    }

    println!("Initialized BMB project `{}` in {}", name, path.display());
    Ok(())
}

/// Validate project name
fn validate_project_name(name: &str) -> Result<(), ProjectError> {
    if name.is_empty() {
        return Err(ProjectError::InvalidName(
            "Project name cannot be empty".to_string(),
        ));
    }

    if !name.chars().next().unwrap().is_alphabetic() && !name.starts_with('_') {
        return Err(ProjectError::InvalidName(
            "Project name must start with a letter or underscore".to_string(),
        ));
    }

    if !name
        .chars()
        .all(|c| c.is_alphanumeric() || c == '_' || c == '-')
    {
        return Err(ProjectError::InvalidName(
            "Project name can only contain letters, numbers, underscores, and hyphens".to_string(),
        ));
    }

    Ok(())
}

/// Create binary project template
fn create_bin_template(path: &Path, name: &str) -> Result<(), std::io::Error> {
    fs::write(path.join("src/main.bmb"), generate_main_content(name))?;
    Ok(())
}

/// Create library project template
fn create_lib_template(path: &Path, name: &str) -> Result<(), std::io::Error> {
    fs::write(path.join("src/lib.bmb"), generate_lib_content(name))?;
    Ok(())
}

/// Generate main.bmb content for binary projects
fn generate_main_content(name: &str) -> String {
    format!(
        r#"-- {name} - BMB Project
-- Generated by gotgan

fn main() -> i64 =
  println("Hello from {name}!");
  0;
"#,
        name = name
    )
}

/// Generate lib.bmb content for library projects
fn generate_lib_content(name: &str) -> String {
    format!(
        r#"-- {name} - BMB Library
-- Generated by gotgan

-- Add a simple function with a contract
fn add(a: i64, b: i64) -> i64
  post ret == a + b
= a + b;
"#,
        name = name
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::env::temp_dir;

    #[test]
    fn test_validate_project_name() {
        assert!(validate_project_name("hello").is_ok());
        assert!(validate_project_name("my_project").is_ok());
        assert!(validate_project_name("my-project").is_ok());
        assert!(validate_project_name("project123").is_ok());
        assert!(validate_project_name("_private").is_ok());

        assert!(validate_project_name("").is_err());
        assert!(validate_project_name("123abc").is_err());
        assert!(validate_project_name("hello world").is_err());
    }

    #[test]
    fn test_generate_main_content() {
        let content = generate_main_content("test");
        assert!(content.contains("fn main()"));
        assert!(content.contains("Hello from test"));
    }

    #[test]
    fn test_generate_lib_content() {
        let content = generate_lib_content("test");
        assert!(content.contains("fn add"));
        assert!(content.contains("post ret == a + b"));
    }

    #[test]
    fn test_create_project() {
        let temp = temp_dir().join("gotgan_test_create");
        let _ = fs::remove_dir_all(&temp);

        let result = create_project("test_proj", &temp, false);
        assert!(result.is_ok());
        assert!(temp.join("gotgan.toml").exists());
        assert!(temp.join("src/main.bmb").exists());

        // Cleanup
        let _ = fs::remove_dir_all(&temp);
    }
}
